language: python

python:
  - 3.6

sudo: required
dist: trusty
addons:
  postgresql: "9.6"

services:
  - postgresql

env:
  - DJANGO_SETTINGS_MODULE="decide.settings"

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "create user decide with password 'decide'" -U postgres
  - psql -c "create database decide owner decide" -U postgres

script:
  - python ./decide/manage.py makemigrations
  - python ./decide/manage.py migrate
#  - python ./decide/manage.py compilemessages
#c  - python ./decide/manage.py test ./decide
  - if [[ $TRAVIS_BRANCH == "master" ]] && [[ $DEPLOY_TRAVIS == "1" ]]; then git archive --format zip --output ./decide.zip master; echo "perfecto"; fi

before_deploy:
- git config --local user.name $USER_TRAVIS
- git config --local user.email $EMAIL_TRAVIS
- export YEAR=`date +"%Y"`  
- export GIT_TAG=v2.0.$TRAVIS_BUILD_NUMBER-$YEAR
- git tag -a $GIT_TAG -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"

deploy:
  provider: releases
  api-key:
    secure: $TOKEN_TRAVIS
  file: "./decide.zip"
  skip_cleanup: true
  on:
    branch: master
    condition: $DEPLOY_TRAVIS = 1
    tags: false

notifications:
  email: false
      
branches:
  only:
  - master
  - develop